### ISSUE TITLE
Realtà Aumentata

### ISSUE THREAD

**Issue by giuseppezileni** [mappiamo/mapi-app#2]
Bisogna creare una bussola, attraverso la camera del dispositivo, che indichi il POI più vicino a partire dalla posizione del device.
Esistono alcune soluzioni come queste:
* http://fabricjs.com
* https://github.com/mbppower/CordovaCameraPreview
che permettono di interagire con la camera del dispositivo.

**Comment by giuseppezileni** [comment]
Il plugin https://github.com/mbppower/CordovaCameraPreview non si può usare, manda in crash l'App.

**Comment by giuseppezileni** [comment]
L'idea è una bussola che viene animata in base all'orientamento del device, per cercare i POI più vicini nella direzione, con tutte le informazioni di routing per raggiungere il luogo.
![compass_380](https://cloud.githubusercontent.com/assets/6775950/9012436/23260e7a-37b5-11e5-9a5f-8ae7e670da45.png)

**Comment by bertalan** [comment]
Potrebbe essere molto interessante. Non si riesce ad attivare la camera? 
Questa soluzione mi da l'idea di un navigatore e non di una AR.

**Comment by giuseppezileni** [comment]
OK. Provo a creare questa procedura:
1. Attivo la camera
2. L'utente scatta la foto
3. Insieme alla foto compare la bussola con le indicazioni geografiche ed il POI più vicino
4. Compare anche un button "vuoi raggiungere il percorso ?"
5 Compare il percorso di routing.

**Comment by bertalan** [comment]
Attivi la camera, ma non serve lo scatto.
Compare la bussola con le indicazioni geo
Compare la lista dei POI
Click sul POI che mostra la scheda del POI.

**Comment by giuseppezileni** [comment]
https://github.com/mbppower/CordovaCameraPreview è un plugin terribile, oltre a mandare in crash il dispositivo, non è prevista una versione per WP. Inutilizzabile.
Ho provato con una soluzione alternativa che ho pubblicato nella versione 1.1.0, una bussola che indica la direzione, e con un click si leggono la lista dei POI.
